import { useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router'
import { useMutation, useQuery } from '@tanstack/react-query'
import { api } from '@/api/client'
import { useMe } from '@/auth/useMe'
import { PageContainer } from '@/layout/PageContainer'
import { Alert, Badge, Button, ButtonLink, Card, EmptyState, ErrorAlert, Field, Money, PageHeader, QueryView, Steps, TextInput } from '@/ui'
import type { Catalogue, ServiceDetail } from './types'
export function CataloguePage() {
  const [q, setQ] = useState(''); const [category, setCategory] = useState('')
  const data = useQuery({ queryKey: ['services', 'catalogue', q, category], queryFn: ({ signal }) => api.get<Catalogue>('/api/public/services', { query: { q, category: category || undefined }, signal }) })
  return <PageContainer><PageHeader title="Council services" description="Find a service, prepare your documents and follow your request to a result." /><Field label="Search services" required><TextInput type="search" value={q} onChange={(e) => setQ(e.target.value)} placeholder="Try hall, pothole or planning certificate" /></Field><QueryView query={data}>{(catalogue) => <><div className="my-5 flex flex-wrap gap-2" aria-label="Service categories"><Button variant={!category ? 'primary' : 'secondary'} aria-pressed={!category} onClick={() => setCategory('')}>All services</Button>{catalogue.categories.map((c) => <Button key={c} variant={category === c ? 'primary' : 'secondary'} aria-pressed={category === c} onClick={() => setCategory(c)}>{c}</Button>)}</div><p className="mb-3 text-muted" aria-live="polite">{catalogue.items.length} services found</p><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{catalogue.items.map((s) => <Card key={s.id} title={<Link className="link" to={`/services/${s.slug}`}>{s.name}</Link>} footer={<ButtonLink to={`/services/${s.slug}`} variant="secondary">View service</ButtonLink>}><Badge>{s.department}</Badge><p className="mt-3">{s.summary}</p><p className="mt-3 text-sm text-muted">{s.outcome}</p><p className="mt-3 text-xs text-muted">{s.price_note}</p></Card>)}</div>{!catalogue.items.length && <EmptyState title="No matching services" description="Try a different word or choose all categories." />}</>}</QueryView></PageContainer>
}
export function ServicePage() {
  const { slug } = useParams(); const navigate = useNavigate(); const me = useMe()
  const data = useQuery({ queryKey: ['services', 'service', slug], queryFn: () => api.get<ServiceDetail>(`/api/public/services/${slug}`) })
  const start = useMutation({ mutationFn: () => api.post<{ id: number }>(`/api/services/${slug}/drafts`, {}), onSuccess: (d) => navigate(`/my/drafts/${d.id}`) })
  return <PageContainer><QueryView query={data}>{({ service, definition: def, prices, price_schedule_note }) => <><PageHeader title={service.name} eyebrow={service.department} description={def.summary} breadcrumbs={[{ label: 'Services', to: '/services' }, { label: service.name }]} /><div className="grid gap-6 lg:grid-cols-[2fr_1fr]"><div className="space-y-6"><Card title="What you get"><p>{def.outcome}</p></Card><Card title="Who can apply"><p>{def.who_can_apply}</p></Card><Card title="Documents to prepare">{def.documents.length ? <ul className="list-disc space-y-2 pl-5">{def.documents.map((d) => <li key={d.key}>{d.label}{d.required ? ' — required' : ' — optional'}</li>)}</ul> : <p>No supporting documents are needed.</p>}</Card><Card title="How the price is calculated"><p>{def.price_note}</p><p className="my-3 font-semibold">{price_schedule_note}</p>{prices.map((p) => <p key={p.code} className="flex flex-wrap justify-between gap-2 py-2 border-b border-line"><span>{p.name}</span><span><Money cents={p.amount_cents} /> per {p.unit}</span></p>)}{!prices.length && <p className="mt-3 text-muted">Council will advise if a fee applies.</p>}</Card></div><div className="space-y-6"><Card title="What happens next"><Steps steps={def.workflow.steps.map((s) => ({ key: s.key, label: s.applicant_label || s.label }))} /></Card><Card title="Start your request">{me.data?.user ? <Button fullWidth loading={start.isPending} onClick={() => start.mutate()}>Start request</Button> : <><ButtonLink to="/login" fullWidth>Sign in to start</ButtonLink>{me.data?.demo_mode && <p className="mt-3"><Link className="link" to="/demo">Try a fictional demo persona</Link></p>}</>}{start.error && <ErrorAlert error={start.error} />}<Alert title="Request first, decision later">Your request is only received when you submit it. A booking is confirmed separately.</Alert></Card></div></div></>}</QueryView></PageContainer>
}
