import { useState } from 'react'
import { Link } from 'react-router'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { api } from '@/api/client'
import { Alert, Button, Card, DateTime, EmptyState, ErrorAlert, Field, FileInput, PageHeader, QueryView, StatusPill, Table } from '@/ui'
interface Report { id: number; status: string; filename?: string; report: { items: { index: number; item: { slug: string; name: string }; valid: boolean; issues: { path: string; message: string }[]; service_id?: number; version_id?: number; link?: string }[] } }
export function ImportsPage() {
  const client = useQueryClient(); const [file, setFile] = useState<File | null>(null); const [report, setReport] = useState<Report | null>(null)
  const q = useQuery({ queryKey: ['services', 'imports'], queryFn: () => api.get<{ items: { id: number; filename: string; status: string; created_at: string }[] }>('/api/admin/service-imports') })
  const upload = useMutation({ mutationFn: () => { if (!file) throw new Error('Choose a JSON file.'); return api.upload<Report>('/api/admin/service-imports', { file }) }, onSuccess: (r) => { setReport(r); client.invalidateQueries({ queryKey: ['services', 'imports'] }) } })
  const apply = useMutation({ mutationFn: () => api.post<Report>(`/api/admin/service-imports/${report?.id}/apply`, {}), onSuccess: (r) => { setReport(r); client.invalidateQueries({ queryKey: ['services'] }) } })
  const open = useMutation({ mutationFn: (id: number) => api.get<Report>(`/api/admin/service-imports/${id}`), onSuccess: setReport })
  return <><PageHeader title="Bulk service import" description="Check a JSON file first, then create drafts for valid items. Imports never publish a service." /><Card title="Validate an import"><Field label="Service definitions JSON file" required hint="An array of slug, name, category, module, department and definition objects."><FileInput accept="application/json,.json" onChange={(e) => setFile(e.target.files?.[0] ?? null)} /></Field><Button className="mt-4" disabled={!file} loading={upload.isPending} onClick={() => upload.mutate()}>Upload and validate</Button>{upload.error && <ErrorAlert error={upload.error} />}</Card>{report && <Card title={`Import ${report.id} validation report`}><StatusPill status={report.status} /><div className="mt-4 space-y-3">{report.report.items.map((r) => <div key={r.index} className="rounded-lg border border-line p-4"><h3 className="font-semibold">{r.item.name || r.item.slug || `Item ${r.index + 1}`}</h3><p>{r.valid ? 'Valid — ready for a draft' : 'Needs corrections'}</p>{r.issues.map((i, n) => <p key={n} className="text-danger">{i.path}: {i.message}</p>)}{r.link && <Link className="link" to={r.link}>Open created draft version {r.version_id}</Link>}</div>)}</div>{report.status !== 'applied' && <Button className="mt-5" loading={apply.isPending} disabled={!report.report.items.some((r) => r.valid)} onClick={() => apply.mutate()}>Create drafts for valid items</Button>}{apply.error && <ErrorAlert error={apply.error} />}{report.status === 'applied' && <Alert tone="success" title="Drafts created">Review every field and rule in the service builder before publishing.</Alert>}</Card>}<Card title="Import history"><QueryView query={q}>{({ items }) => <Table caption="Uploaded service imports" rows={items} rowKey={(i) => i.id} columns={[{ key: 'name', header: 'File', cell: (i) => <Button variant="ghost" onClick={() => open.mutate(i.id)}>{i.filename}</Button> }, { key: 'status', header: 'Status', cell: (i) => <StatusPill status={i.status} /> }, { key: 'date', header: 'Uploaded', cell: (i) => <DateTime value={i.created_at} /> }]} empty={<EmptyState title="No imports yet" />} />}</QueryView>{open.error && <ErrorAlert error={open.error} />}</Card></>
}
