import { useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { api, isApiError } from '@/api/client'
import { useMe } from '@/auth/useMe'
import { PageHeader, Card, QueryView, EmptyState, DateTime, StatusPill, Field, TextInput, Textarea, Select, Button, ErrorAlert, Alert, useToast } from '@/ui'
import type { Document, Exhibition, ExhibitionDetail, Item, Rect } from './types'

export function ExhibitionsPage() {
  const q = useQuery({ queryKey: ['documents', 'exhibitions'], queryFn: () => api.get<Exhibition[]>('/api/exhibitions') })
  return <div className="space-y-6 break-words"><PageHeader title="Exhibitions" description="Prepare a public notice, redact chosen document versions and ask another staff member to approve publication." /><CreateExhibition /><QueryView query={q}>{rows => rows.length ? rows.map(e => <Card key={e.id} title={e.title} actions={<StatusPill status={e.status} />}><p>Comments close <DateTime value={e.closes_at} /></p><Link className="link inline-block py-3" to={`/staff/exhibitions/${e.id}`}>Edit notice / review submissions</Link></Card>) : <EmptyState title="No exhibitions yet" />}</QueryView></div>
}
function CreateExhibition() {
  const [caseId, setCase] = useState(''), [title, setTitle] = useState(''), [summary, setSummary] = useState(''), [opens, setOpens] = useState(''), [closes, setCloses] = useState('')
  const navigate = useNavigate()
  const m = useMutation({ mutationFn: async () => { const d = await api.get<{ id: number; revision: number }>(`/api/exhibitions/lookup/${encodeURIComponent(caseId.trim())}`); return api.post<{ id: number }>('/api/exhibitions', { case_id: d.id, title, summary, opens_at: opens, closes_at: closes, expected_revision: d.revision }) }, onSuccess: e => navigate(`/staff/exhibitions/${e.id}`) })
  const errors = isApiError(m.error) ? m.error.fields : {}
  return <Card title="Prepare exhibition"><form className="space-y-4" onSubmit={e => { e.preventDefault(); m.mutate() }}><Field label="Building request number (NSH)" required error={errors.case_id}><TextInput placeholder="NSH-2026-00001" value={caseId} onChange={e => setCase(e.target.value)} /></Field><Field label="Public title" required error={errors.title}><TextInput value={title} onChange={e => setTitle(e.target.value)} /></Field><Field label="Public summary" required error={errors.summary}><Textarea value={summary} onChange={e => setSummary(e.target.value)} /></Field><WindowInputs opens={opens} closes={closes} setOpens={setOpens} setCloses={setCloses} errors={errors} />{m.error && <ErrorAlert error={m.error} />}<Button type="submit" loading={m.isPending}>Create draft exhibition</Button></form></Card>
}
function WindowInputs({ opens, closes, setOpens, setCloses, errors }: { opens: string; closes: string; setOpens: (s: string) => void; setCloses: (s: string) => void; errors: Record<string, string> }) {
  return <div className="grid gap-4 sm:grid-cols-2"><Field label="Opens at" required error={errors.opens_at} hint="ISO date/time with Norfolk offset, e.g. 2026-10-07T09:00:00+12:00"><TextInput value={opens} onChange={e => setOpens(e.target.value)} /></Field><Field label="Closes at" required error={errors.closes_at} hint="Include the timezone offset."><TextInput value={closes} onChange={e => setCloses(e.target.value)} /></Field></div>
}
export function ExhibitionPage() {
  const { id } = useParams(), qc = useQueryClient(), toast = useToast(), me = useMe().data
  const q = useQuery({ queryKey: ['documents', 'exhibition', id], queryFn: () => api.get<ExhibitionDetail>(`/api/exhibitions/${id}`) })
  const m = useMutation({ mutationFn: () => api.post(`/api/exhibitions/${id}/publish`, { expected_revision: q.data?.revision }), onSuccess: async () => { toast.success('Redacted public copies published.'); await qc.invalidateQueries({ queryKey: ['documents'] }) } })
  const withdraw = useMutation({mutationFn:()=>api.post(`/api/exhibitions/${id}/withdraw`,{expected_revision:q.data?.revision}),onSuccess:()=>qc.invalidateQueries({queryKey:['documents']})})
  return <QueryView query={q}>{d => <div className="space-y-6 break-words"><PageHeader title={d.exhibition.title} description={d.exhibition.summary} breadcrumbs={[{ label: 'Exhibitions', to: '/staff/exhibitions' }, { label: d.exhibition.title }]} meta={<StatusPill status={d.exhibition.status} />} />{d.exhibition.status === 'draft' && <><NoticeEditor key={`${id}-${d.revision}`} data={d} /> <ItemEditor key={`new-${d.revision}`} data={d} /></>}
    {d.items.map(item => d.exhibition.status === 'draft' ? <ItemEditor key={`${item.id}-${d.revision}`} data={d} item={item} /> : <Card key={item.id} title={item.title}><a className="link" href={`/api/public/exhibitions/${id}/items/${item.id}/file`}>Download published redacted copy</a></Card>)}
    {d.exhibition.status === 'draft' && <Card title="Publication approval"><Alert title="A second staff member must approve">Review every page and rectangle before publishing. Public files are new raster copies with no source text layer. Preparer user ID: {d.exhibition.prepared_by}.</Alert>{me?.user?.id === d.exhibition.prepared_by ? <p className="mt-4">Ask another Planning specialist or manager to review and publish.</p> : <Button onClick={() => m.mutate()} loading={m.isPending} disabled={!d.items.length}>Approve and publish redacted copies</Button>}{m.error && <ErrorAlert error={m.error} />}</Card>}
    {me?.roles.includes('manager') && ['open','closed'].includes(d.exhibition.status) && <><Button variant="danger-outline" onClick={()=>withdraw.mutate()} loading={withdraw.isPending}>Withdraw exhibition</Button><ErrorAlert error={withdraw.error}/></>}
    <Submissions data={d} />
  </div>}</QueryView>
}
function NoticeEditor({ data }: { data: ExhibitionDetail }) {
  const e = data.exhibition, [title, setTitle] = useState(e.title), [summary, setSummary] = useState(e.summary), [opens, setOpens] = useState(e.opens_at), [closes, setCloses] = useState(e.closes_at), qc = useQueryClient()
  const m = useMutation({ mutationFn: () => api.put(`/api/exhibitions/${e.id}`, { case_id: e.case_id, title, summary, opens_at: opens, closes_at: closes, expected_revision: data.revision }), onSuccess: () => qc.invalidateQueries({ queryKey: ['documents'] }) }), errors = isApiError(m.error) ? m.error.fields : {}
  return <Card title="Notice and window"><form className="space-y-4" onSubmit={ev => { ev.preventDefault(); m.mutate() }}><Field label="Public title" required error={errors.title}><TextInput value={title} onChange={ev => setTitle(ev.target.value)} /></Field><Field label="Public summary" required error={errors.summary}><Textarea value={summary} onChange={ev => setSummary(ev.target.value)} /></Field><WindowInputs opens={opens} closes={closes} setOpens={setOpens} setCloses={setCloses} errors={errors} />{m.error && <ErrorAlert error={m.error} />}<Button type="submit" loading={m.isPending}>Save notice</Button></form></Card>
}
function ItemEditor({ data, item }: { data: ExhibitionDetail; item?: Item }) {
  const [source, setSource] = useState(String(item?.source_document_version_id ?? '')), [title, setTitle] = useState(item?.title ?? ''), [rects, setRects] = useState<Rect[]>(item ? JSON.parse(item.redactions_json) as Rect[] : []), [previewFailed, setPreviewFailed] = useState(false), [page, setPage] = useState(1), [start, setStart] = useState<{ x: number; y: number } | null>(null)
  const docs = useQuery({ queryKey: ['documents', 'case', data.exhibition.case_id], queryFn: () => api.get<Document[]>(`/api/cases/${data.exhibition.case_id}/documents`) }), qc = useQueryClient()
  const m = useMutation({ mutationFn: () => { const body = { source_document_version_id: Number(source), title, redactions: rects, expected_revision: data.revision }; return item ? api.put(`/api/exhibitions/${data.exhibition.id}/items/${item.id}`, body) : api.post(`/api/exhibitions/${data.exhibition.id}/items`, body) }, onSuccess: () => qc.invalidateQueries({ queryKey: ['documents'] }) }), errors = isApiError(m.error) ? m.error.fields : {}
  const update = (index: number, key: keyof Rect, value: number) => setRects(rects.map((r, i) => i === index ? { ...r, [key]: value } : r))
  return <Card title={item ? `Redact: ${item.title}` : 'Add publication item'}><form className="space-y-4" onSubmit={e => { e.preventDefault(); m.mutate() }}><Field label="Exact source version" required error={errors.source_document_version_id}><Select value={source} onChange={e => setSource(e.target.value)} placeholder="Choose a version" options={(docs.data ?? []).flatMap(d => d.versions.map(v => ({ value: String(v.id), label: `${d.title} v${v.version}` })))} /></Field><Field label="Public document title" required error={errors.title}><TextInput value={title} onChange={e => setTitle(e.target.value)} /></Field>
    {item && source === String(item.source_document_version_id) && <><Field label="Preview page" hint="Use the page number to review each page. The preview shows the staff-only source."><TextInput type="number" min={1} max={30} value={page} onChange={e => { setPage(Number(e.target.value)); setPreviewFailed(false) }} /></Field><div className="relative touch-none max-w-3xl" onPointerDown={e => { const b = e.currentTarget.getBoundingClientRect(); setStart({ x: (e.clientX - b.left) / b.width, y: (e.clientY - b.top) / b.height }); e.currentTarget.setPointerCapture(e.pointerId) }} onPointerUp={e => { if (!start) return; const b = e.currentTarget.getBoundingClientRect(), x = Math.max(0, Math.min(1, (e.clientX - b.left) / b.width)), y = Math.max(0, Math.min(1, (e.clientY - b.top) / b.height)); if (Math.abs(x - start.x) > .001 && Math.abs(y - start.y) > .001) setRects([...rects, { page, x: Math.min(x, start.x), y: Math.min(y, start.y), w: Math.abs(x - start.x), h: Math.abs(y - start.y) }]); setStart(null) }}><img onError={() => setPreviewFailed(true)} onLoad={() => setPreviewFailed(false)} className="w-full border border-line" alt={`Staff-only source page ${page}. Use numeric rectangle controls below to redact with a keyboard.`} src={`/api/exhibitions/${data.exhibition.id}/items/${item.id}/pages/${page}.png`} draggable={false} />{rects.filter(r => r.page === page).map((r, i) => <div key={i} className="absolute bg-ink opacity-80 pointer-events-none" style={{ left: `${r.x * 100}%`, top: `${r.y * 100}%`, width: `${r.w * 100}%`, height: `${r.h * 100}%` }} />)}</div></>}
    {item && <details><summary className="link py-3">Review saved redacted public output</summary><img className="w-full max-w-3xl border border-line" alt={`Redacted public output page ${page}`} src={`/api/exhibitions/${data.exhibition.id}/items/${item.id}/redacted-pages/${page}.png?revision=${data.revision}`} /><p>Save all rectangles before reviewing this output.</p></details>}
    {previewFailed && <Alert tone="warning" title="Could not load this page">Check the page number and saved source version.</Alert>}
    {item && source !== String(item.source_document_version_id) && <Alert title="Save the source change first">Save this item to preview the chosen source and check its redactions.</Alert>}
    <p className="text-muted">Draw on the source preview, or use the keyboard controls. Coordinates are page fractions from the top left (0–1). Save the item before previewing a new source.</p>
    {rects.map((r, index) => <fieldset key={index} className="border border-line p-3 rounded"><legend>Redaction {index + 1}</legend><div className="grid grid-cols-2 sm:grid-cols-5 gap-3">{(['page', 'x', 'y', 'w', 'h'] as const).map(key => <Field key={key} label={key === 'page' ? 'Page' : ({ x: 'Left', y: 'Top', w: 'Width', h: 'Height' } as const)[key]}><TextInput type="number" min={key === 'page' ? 1 : 0} max={key === 'page' ? 30 : 1} step={key === 'page' ? 1 : .001} value={r[key]} onChange={e => update(index, key, Number(e.target.value))} /></Field>)}</div><Button variant="ghost" onClick={() => setRects(rects.filter((_, i) => i !== index))}>Remove rectangle {index + 1}</Button></fieldset>)}
    <Button variant="secondary" onClick={() => setRects([...rects, { page, x: .1, y: .1, w: .3, h: .1 }])}>Add rectangle using keyboard controls</Button>{errors.redactions && <p role="alert" className="text-danger">{errors.redactions}</p>}{m.error && <ErrorAlert error={m.error} />}<Button type="submit" loading={m.isPending}>{item ? 'Save source and redactions' : 'Add item'}</Button>
  </form></Card>
}
function Submissions({ data }: { data: ExhibitionDetail }) {
  const id = data.exhibition.id, qc = useQueryClient(), q = useQuery({ queryKey: ['documents', 'submissions', id], queryFn: () => api.get<{ id: number; name: string; email: string; body: string; status: string; created_at: string }[]>(`/api/exhibitions/${id}/submissions`) })
  const m = useMutation({ mutationFn: (sid: number) => api.post(`/api/exhibitions/${id}/submissions/${sid}/consider`, { expected_revision: data.revision }), onSuccess: () => qc.invalidateQueries({ queryKey: ['documents'] }) })
  return <Card title="Public submissions">{m.error && <ErrorAlert error={m.error} />}<QueryView query={q}>{rows => rows.length ? rows.map(s => <section key={s.id} className="py-4 border-b border-line"><h3 className="font-semibold">{s.name}</h3><p>{s.email}</p><DateTime value={s.created_at} /><p className="break-words whitespace-pre-wrap mt-3">{s.body}</p><StatusPill status={s.status} />{s.status === 'received' && <Button variant="secondary" loading={m.isPending} onClick={() => m.mutate(s.id)}>Mark considered</Button>}</section>) : <EmptyState title="No submissions received" />}</QueryView></Card>
}
