import { useRef, useState } from 'react'
import { useMutation, useQuery } from '@tanstack/react-query'
import { Link, useSearchParams } from 'react-router'
import { api, isApiError, newIdempotencyKey } from '@/api/client'
import type { Answers } from '@/api/types'
import { Alert, Button, Card, ErrorAlert, Field, PageHeader, QueryView, Select, TextInput } from '@/ui'
import { FormRenderer } from '../services/FormRenderer'
import type { Catalogue, ServiceDetail } from '../services/types'
import type { DraftDetail } from './types'
/** Assisted intake. `?service=<slug>` (from a service page) preselects the service. */
export function IntakePage() {
  const [params] = useSearchParams()
  const [service, setService] = useState(params.get('service') ?? ''); const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [phone, setPhone] = useState(''); const [channel, setChannel] = useState('phone'); const [answers, setAnswers] = useState<Answers>({}); const [draft, setDraft] = useState<number | null>(null); const [review, setReview] = useState(false)
  const key = useRef(newIdempotencyKey())
  const catalogue = useQuery({ queryKey: ['services', 'catalogue'], queryFn: () => api.get<Catalogue>('/api/public/services') })
  const detail = useQuery({ queryKey: ['services', 'service', service], queryFn: () => api.get<ServiceDetail>(`/api/public/services/${service}`), enabled: !!service })
  const frozen = useQuery({ queryKey: ['cases', 'intake-draft', draft], queryFn: () => api.get<DraftDetail>(`/api/cases/${draft}/draft`), enabled: draft !== null })
  const save = useMutation({ mutationFn: (draftOnly: boolean) => api.post<{ id: number; number: string | null }>('/api/staff/intake', { service, applicant_name: name, applicant_email: email || null, applicant_phone: phone || null, channel, answers, draft_only: draftOnly, case_id: draft }, { idempotencyKey: key.current }), onError: () => setReview(false), onSuccess: (d) => { if (!d.number) { setDraft(d.id); key.current = newIdempotencyKey() } } })
  const errors = isApiError(save.error) ? save.error.fields : {}
  const changed = () => { key.current = newIdempotencyKey(); save.reset() }
  const definition = frozen.data?.definition ?? detail.data?.definition
  return <><PageHeader title="Assisted intake" description="Record a phone, walk-in, email or post request for someone without an account." />{save.data?.number ? <Alert tone="success" title={`Request ${save.data.number} received`}><p>Read this reference number to the applicant. Receiving the request does not approve it or confirm a booking.</p><Link className="link" to={`/staff/cases/${save.data.id}`}>Open request workspace</Link></Alert> : <div className="space-y-5"><Card title="Service and applicant"><div className="grid gap-4 sm:grid-cols-2"><Field label="Service" required error={errors.service}><Select value={service} onChange={(e) => { setService(e.target.value); setAnswers({}); changed() }} disabled={draft !== null} placeholder="Choose a service" options={catalogue.data?.items.map((s) => ({ value: s.slug, label: s.name })) ?? []} /></Field><Field label="Received by" required error={errors.channel}><Select value={channel} onChange={(e) => { setChannel(e.target.value); changed() }} disabled={draft !== null} options={[{ value: 'phone', label: 'Phone' }, { value: 'walk_in', label: 'Walk in' }, { value: 'email', label: 'Email' }, { value: 'post', label: 'Post' }]} /></Field><Field label="Applicant name" required error={errors.applicant_name}><TextInput value={name} disabled={draft !== null} onChange={(e) => { setName(e.target.value); changed() }} /></Field><Field label="Applicant email" error={errors.applicant_email}><TextInput type="email" value={email} disabled={draft !== null} onChange={(e) => { setEmail(e.target.value); changed() }} /></Field><Field label="Applicant phone" hint="An email address or phone number is required." error={errors.applicant_phone}><TextInput type="tel" value={phone} disabled={draft !== null} onChange={(e) => { setPhone(e.target.value); changed() }} /></Field></div></Card>{service && <QueryView query={detail}>{() => definition && <Card title={review ? 'Review the request' : 'Request details'}><FormRenderer definition={definition} answers={answers} onChange={(a) => { setAnswers(a); changed() }} caseId={draft ?? undefined} errors={errors} disabled={save.isPending} review={review} />{save.error && <ErrorAlert error={save.error} />}<div className="mt-5 flex flex-wrap gap-3">{draft === null && <Button variant="secondary" onClick={() => save.mutate(true)} loading={save.isPending}>Save draft and attach documents</Button>}{review ? <><Button variant="secondary" onClick={() => setReview(false)}>Edit details</Button><Button loading={save.isPending} onClick={() => save.mutate(false)}>Submit assisted request</Button></> : <Button onClick={() => setReview(true)}>Review request</Button>}</div><p className="mt-3 text-sm text-muted" aria-live="polite">{draft ? 'Draft saved. Attach documents above before submitting.' : ''}</p></Card>}</QueryView>}</div>}</>
}
