import { useState } from 'react'
import { Link, useSearchParams } from 'react-router'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { api } from '@/api/client'
import { Button, ButtonLink, Card, DateTime, EmptyState, ErrorAlert, Field, PageHeader, QueryView, Select, StatusPill, Table, TextInput } from '@/ui'
import { humanize } from '@/ui/status'
import { useMe, hasAnyRole } from '@/auth/useMe'
import type { Catalogue } from '../services/types'
import type { CaseList, RequestSummary } from './types'
export function MyRequestsPage() {
  const [page, setPage] = useState(1)
  const data = useQuery({ queryKey: ['cases', 'mine', page], queryFn: () => api.get<CaseList>('/api/my/cases', { query: { page, page_size: 50 } }) })
  const client = useQueryClient()
  const remove = useMutation({ mutationFn: (id: number) => api.delete(`/api/cases/${id}/draft`), onSuccess: () => client.invalidateQueries({ queryKey: ['cases'] }) })
  return <><PageHeader title="My requests" description="Follow requests, answer Council and continue your saved drafts." actions={<ButtonLink to="/services">Find a service</ButtonLink>} />{remove.error && <ErrorAlert error={remove.error} />}<QueryView query={data}>{({ items, total, page_size }) => {
    const sections = [ ['Needs your action', items.filter((c) => c.required_action)], ['Open requests', items.filter((c) => !c.required_action && ['submitted', 'in_progress', 'waiting_on_applicant'].includes(c.status))], ['Drafts', items.filter((c) => c.status === 'draft')], ['Completed and closed', items.filter((c) => !['draft', 'submitted', 'in_progress', 'waiting_on_applicant'].includes(c.status))] ] as const
    return <><div className="space-y-6">{sections.map(([title, rows]) => <Card key={title} title={title}>{rows.length ? <div className="space-y-4">{rows.map((c) => <div key={c.id} className="flex flex-wrap items-start justify-between gap-3 border-b border-line pb-3 last:border-0"><div className="min-w-0"><Link className="link font-semibold" to={c.status === 'draft' ? `/my/drafts/${c.id}` : `/my/cases/${c.id}`}>{c.number ?? 'Continue draft'} — {c.service_name}</Link><p className="mt-1">{c.applicant_status_text}</p>{c.required_action && <p className="mt-2 font-semibold">{c.required_action.body}</p>}<p className="text-sm text-muted">Updated <DateTime value={c.updated_at} /></p></div>{c.status === 'draft' ? <Button variant="ghost" onClick={() => remove.mutate(c.id)} loading={remove.isPending}>Delete draft</Button> : <StatusPill status={c.status} label={c.applicant_status_text} />}</div>)}</div> : <EmptyState title={title === 'Needs your action' ? 'Nothing needs your action' : `No ${title.toLowerCase()}`} description={{ 'Needs your action': 'You are up to date. We will let you know when a reply or document is needed.', 'Open requests': 'Find a service to start a new request. You can follow its progress here.', 'Drafts': 'Requests you start and save appear here so you can finish them later.', 'Completed and closed': 'Your results and closed requests will stay here for reference.' }[title]} />}</Card>)}</div><div className="mt-4 flex flex-wrap items-center gap-3"><Button variant="secondary" disabled={page <= 1} onClick={() => setPage(page - 1)}>Previous</Button><p aria-live="polite">Page {page} — {total} requests</p><Button variant="secondary" disabled={page * page_size >= total} onClick={() => setPage(page + 1)}>Next</Button></div></>
  }}</QueryView></>
}
export function StaffHomePage() {
  const me = useMe()
  return <><PageHeader title="Staff workspace" description="Choose a queue or record an assisted request." actions={hasAnyRole(me.data, ['intake']) ? <ButtonLink to="/staff/intake">Assisted intake</ButtonLink> : undefined} /><div className="mb-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[['new', 'New'], ['mine', 'Mine'], ['waiting', 'Waiting on applicant'], ['overdue', 'Overdue']].map(([q, label]) => <Card key={q} title={label} footer={<ButtonLink to={`/staff/cases?queue=${q}`} variant="secondary">Open queue</ButtonLink>}><p>Review requests in this queue.</p></Card>)}</div><StaffCaseList embedded /></>
}
export function StaffCaseList({ embedded = false }: { embedded?: boolean }) {
  const [params, setParams] = useSearchParams(); const [search, setSearch] = useState(params.get('q') ?? '')
  const queue = params.get('queue') ?? 'all'; const service = params.get('service') ?? ''; const status = params.get('status') ?? ''; const page = Number(params.get('page') ?? '1')
  const update = (key: string, value: string) => { const next = new URLSearchParams(params); next.set(key, value); if (key !== 'page') next.delete('page'); setParams(next) }
  const catalogue = useQuery({ queryKey: ['services', 'catalogue'], queryFn: () => api.get<Catalogue>('/api/public/services') })
  const data = useQuery({ queryKey: ['cases', 'staff-list', queue, service, status, search, page], queryFn: ({ signal }) => api.get<CaseList>('/api/staff/cases', { query: { queue, service: service || undefined, status: status || undefined, q: search, page }, signal }) })
  return <>{!embedded && <PageHeader title="Cases" description="Search and filter the requests you can access." />}<div className="mb-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Field label="Search reference, applicant or details" required><TextInput type="search" value={search} onChange={(e) => { setSearch(e.target.value); update('q', e.target.value) }} /></Field><Field label="Queue" required><Select value={queue} onChange={(e) => update('queue', e.target.value)} options={[{ value: 'all', label: 'All' }, { value: 'new', label: 'New' }, { value: 'mine', label: 'Mine' }, { value: 'waiting', label: 'Waiting on applicant' }, { value: 'overdue', label: 'Overdue' }]} /></Field><Field label="Service" required><Select value={service} onChange={(e) => update('service', e.target.value)} options={[{ value: '', label: 'All services' }, ...(catalogue.data?.items.map((s) => ({ value: s.slug, label: s.name })) ?? [])]} /></Field><Field label="Status" required><Select value={status} onChange={(e) => update('status', e.target.value)} options={[{ value: '', label: 'All statuses' }, ...['draft', 'submitted', 'in_progress', 'waiting_on_applicant', 'completed', 'refused', 'cancelled'].map((s) => ({ value: s, label: humanize(s) }))]} /></Field></div><QueryView query={data}>{(result) => <><CaseTable rows={result.items} /><div className="mt-4 flex flex-wrap items-center gap-3"><Button variant="secondary" disabled={page <= 1} onClick={() => update('page', String(page - 1))}>Previous</Button><p aria-live="polite">Page {page} — {result.total} requests</p><Button variant="secondary" disabled={page * result.page_size >= result.total} onClick={() => update('page', String(page + 1))}>Next</Button></div></>}</QueryView></>
}
function CaseTable({ rows }: { rows: RequestSummary[] }) {
  return <Table caption="Requests" rows={rows} rowKey={(c) => c.id} columns={[{ key: 'number', header: 'Reference', cell: (c) => <Link className="link" to={`/staff/cases/${c.id}`}>{c.number ?? 'Draft'}</Link> }, { key: 'service', header: 'Service', cell: (c) => c.service_name }, { key: 'applicant', header: 'Applicant', cell: (c) => c.applicant_name }, { key: 'status', header: 'Status', cell: (c) => <StatusPill status={c.status} /> }, { key: 'updated', header: 'Updated', cell: (c) => <DateTime value={c.updated_at} />, className: 'hidden md:table-cell' }]} empty={<EmptyState title="No matching requests" description="Try another queue or filter." />} />
}
